package org.obl.hb.css

import org.obl.hb.ValueRenderer 

trait Color extends OutlineColorValue with BorderValue with BackgroundValue

object Color {
  def fromTuple3(p: (Int, Int, Int)) = RGB(p._1, p._2, p._3)
}

object Transparent extends Color {
  override def toString = "transparent"
}

class RGB(r: Int, g: Int, b: Int, formatter: (Int, Int, Int) => String) extends Color {
  override def toString = formatter(r, g, b)
}

object RGB {
  def apply(r: Int, g: Int, b: Int) = {
    if (r > 255 || g > 255 || b > 255 || r < 0 || g < 0 || b < 0) throw new Error("unallowed rgb value: RGB(" + r + ", " + g + ", " + b + ")")
    new RGB(r, g, b, (r, g, b) => "#" + HexUtils.toHexString(r) + HexUtils.toHexString(g) + HexUtils.toHexString(b))
  }

  def percentage(r: Int, g: Int, b: Int) = {
    if (r > 100 || g > 100 || b > 100 || r < 0 || g < 0 || b < 0) throw new Error("unallowed rgb value: RGB(" + r + "%, " + g + "%, " + b + "%)")
    new RGB(r, g, b, (r, g, b) => "rgb(" + r + "%," + g + "%," + b + "%)")
  }

}

class NamedColor(name:String) extends ValueRenderer with Color {
  def render = name
}

object Colors {
  val aliceBlue             = new NamedColor("aliceBlue")
  val antiqueWhite          = new NamedColor("antiqueWhite")
  val aqua                  = new NamedColor("aqua")
  val aquamarine            = new NamedColor("aquamarine")
  val azure                 = new NamedColor("azure")
  val beige                 = new NamedColor("beige")
  val bisque                = new NamedColor("bisque")
  val black                 = new NamedColor("black")
  val blanchedalmond        = new NamedColor("blanchedalmond")
  val blue                  = new NamedColor("blue")
  val blueViolet            = new NamedColor("blueViolet")
  val brown                 = new NamedColor("brown")
  val burlywood             = new NamedColor("burlywood")
  val cadetBlue             = new NamedColor("cadetBlue")
  val chartreuse            = new NamedColor("chartreuse")
  val chocolate             = new NamedColor("chocolate")
  val coral                 = new NamedColor("coral")
  val cornflowerBlue        = new NamedColor("cornflowerBlue")
  val cornsilk              = new NamedColor("cornsilk")
  val crimson               = new NamedColor("crimson")
  val cyan                  = new NamedColor("cyan")
  val darkBlue              = new NamedColor("darkBlue")
  val darkCyan              = new NamedColor("darkCyan")
  val darkGoldenrod         = new NamedColor("darkGoldenrod")
  val darkGray              = new NamedColor("darkGray")
  val darkGreen             = new NamedColor("darkGreen")
  val darkGrey              = new NamedColor("darkGrey")
  val darkKhaki             = new NamedColor("darkKhaki")
  val darkMagenta           = new NamedColor("darkMagenta")
  val darkOliveGreen        = new NamedColor("darkOliveGreen")
  val darkOrange            = new NamedColor("darkOrange")
  val darkOrchid            = new NamedColor("darkOrchid")
  val darkRed               = new NamedColor("darkRed")
  val darkSalmon            = new NamedColor("darkSalmon")
  val darkSeaGreen          = new NamedColor("darkSeaGreen")
  val darkSlateBlue         = new NamedColor("darkSlateBlue")
  val darkSlateGray         = new NamedColor("darkSlateGray")
  val darkSlateGrey         = new NamedColor("darkSlateGrey")
  val darkTurquoise         = new NamedColor("darkTurquoise")
  val darkViolet            = new NamedColor("darkViolet")
  val deepPink              = new NamedColor("deepPink")
  val deepSkyBlue           = new NamedColor("deepSkyBlue")
  val dimGray               = new NamedColor("dimGray")
  val dimGrey               = new NamedColor("dimGrey")
  val dodgerBlue            = new NamedColor("dodgerBlue")
  val firebrick             = new NamedColor("firebrick")
  val floralWhite           = new NamedColor("floralWhite")
  val forestGreen           = new NamedColor("forestGreen")
  val fuchsia               = new NamedColor("fuchsia")
  val gainsboro             = new NamedColor("gainsboro")
  val ghostWhite            = new NamedColor("ghostWhite")
  val gold                  = new NamedColor("gold")
  val goldenrod             = new NamedColor("goldenrod")
  val gray                  = new NamedColor("gray")
  val green                 = new NamedColor("green")
  val greenYellow           = new NamedColor("greenYellow")
  val grey                  = new NamedColor("grey")
  val honeydew              = new NamedColor("honeydew")
  val hotPink               = new NamedColor("hotPink")
  val indianRed             = new NamedColor("indianRed")
  val indigo                = new NamedColor("indigo")
  val ivory                 = new NamedColor("ivory")
  val khaki                 = new NamedColor("khaki")
  val lavender              = new NamedColor("lavender")
  val lavenderblush         = new NamedColor("lavenderblush")
  val lawnGreen             = new NamedColor("lawnGreen")
  val lemonchiffon          = new NamedColor("lemonchiffon")
  val lightBlue             = new NamedColor("lightBlue")
  val lightCoral            = new NamedColor("lightCoral")
  val lightCyan             = new NamedColor("lightCyan")
  val lightGoldenrodYellow  = new NamedColor("lightGoldenrodYellow")
  val lightGray             = new NamedColor("lightGray")
  val lightGreen            = new NamedColor("lightGreen")
  val lightGrey             = new NamedColor("lightGrey")
  val lightPink             = new NamedColor("lightPink")
  val lightSalmon           = new NamedColor("lightSalmon")
  val lightSeaGreen         = new NamedColor("lightSeaGreen")
  val lightSkyBlue          = new NamedColor("lightSkyBlue")
  val lightSlateGray        = new NamedColor("lightSlateGray")
  val lightSlateGrey        = new NamedColor("lightSlateGrey")
  val lightSteelBlue        = new NamedColor("lightSteelBlue")
  val lightYellow           = new NamedColor("lightYellow")
  val lime                  = new NamedColor("lime")
  val limeGreen             = new NamedColor("limeGreen")
  val linen                 = new NamedColor("linen")
  val magenta               = new NamedColor("magenta")
  val maroon                = new NamedColor("maroon")
  val mediumAquamarine      = new NamedColor("mediumAquamarine")
  val mediumBlue            = new NamedColor("mediumBlue")
  val mediumOrchid          = new NamedColor("mediumOrchid")
  val mediumPurple          = new NamedColor("mediumPurple")
  val mediumSeaGreen        = new NamedColor("mediumSeaGreen")
  val mediumSlateBlue       = new NamedColor("mediumSlateBlue")
  val mediumSpringGreen     = new NamedColor("mediumSpringGreen")
  val mediumTurquoise       = new NamedColor("mediumTurquoise")
  val mediumVioletred       = new NamedColor("mediumVioletred")
  val midnightBlue          = new NamedColor("midnightBlue")
  val mintCream             = new NamedColor("mintCream")
  val mistyRose             = new NamedColor("mistyRose")
  val moccasin              = new NamedColor("moccasin")
  val navajoWhite           = new NamedColor("navajoWhite")
  val navy                  = new NamedColor("navy")
  val oldlace               = new NamedColor("oldlace")
  val olive                 = new NamedColor("olive")
  val olivedrab             = new NamedColor("olivedrab")
  val orange                = new NamedColor("orange")
  val orangeRed             = new NamedColor("orangeRed")
  val orchid                = new NamedColor("orchid")
  val paleGoldenrod         = new NamedColor("paleGoldenrod")
  val paleGreen             = new NamedColor("paleGreen")
  val paleTurquoise         = new NamedColor("paleTurquoise")
  val paleVioletred         = new NamedColor("paleVioletred")
  val papayawhip            = new NamedColor("papayawhip")
  val peachpuff             = new NamedColor("peachpuff")
  val peru                  = new NamedColor("peru")
  val pink                  = new NamedColor("pink")
  val plum                  = new NamedColor("plum")
  val powderBlue            = new NamedColor("powderBlue")
  val purple                = new NamedColor("purple")
  val red                   = new NamedColor("red")
  val rosyBrown             = new NamedColor("rosyBrown")
  val royalBlue             = new NamedColor("royalBlue")
  val saddleBrown           = new NamedColor("saddleBrown")
  val salmon                = new NamedColor("salmon")
  val sandyBrown            = new NamedColor("sandyBrown")
  val seaGreen              = new NamedColor("seaGreen")
  val seashell              = new NamedColor("seashell")
  val sienna                = new NamedColor("sienna")
  val silver                = new NamedColor("silver")
  val skyBlue               = new NamedColor("skyBlue")
  val slateBlue             = new NamedColor("slateBlue")
  val slateGray             = new NamedColor("slateGray")
  val slateGrey             = new NamedColor("slateGrey")
  val snow                  = new NamedColor("snow")
  val springGreen           = new NamedColor("springGreen")
  val steelBlue             = new NamedColor("steelBlue")
  val tan                   = new NamedColor("tan")
  val teal                  = new NamedColor("teal")
  val thistle               = new NamedColor("thistle")
  val tomato                = new NamedColor("tomato")
  val turquoise             = new NamedColor("turquoise")
  val violet                = new NamedColor("violet")
  val wheat                 = new NamedColor("wheat")
  val white                 = new NamedColor("white")
  val whitesmoke            = new NamedColor("whitesmoke")
  val yellow                = new NamedColor("yellow")
  val yellowGreen           = new NamedColor("yellowGreen")
}
